# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(
      scheme: "SwiftUI-GiftTrack",
      devices: ["iPhone 8 Plus", "iPhone 13 Pro Max"]
    )
  end

  desc "Creates a signing certificate and provisioning profile"
  lane :certs do
    get_certificates(development: true)
    get_provisioning_profile(development: true)
  end

  lane :build do
    build_app
  end
end

