# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(
      scheme: "SwiftUI-GiftTrack",
      devices: ["iPhone 8 Plus", "iPhone 13 Pro Max"]
    )
  end
end
